
<?php

$categories = array(
    array('pk_i_id' => 1,   'i_position' => 1,  'fk_i_parent_id' => NULL, 's_name' => __('Mobiles &amp; Tablets')),
    array('pk_i_id' => 2,   'i_position' => 2,  'fk_i_parent_id' => NULL, 's_name' => __('Home &amp; Furniture')),
    array('pk_i_id' => 3,   'i_position' => 3,  'fk_i_parent_id' => NULL, 's_name' => __('Clothing & Accessories')),
    array('pk_i_id' => 4,   'i_position' => 4,  'fk_i_parent_id' => NULL, 's_name' => __('Services')),
    array('pk_i_id' => 5,   'i_position' => 5,  'fk_i_parent_id' => NULL, 's_name' => __('Electronics & Computers')),
    array('pk_i_id' => 6,   'i_position' => 6,  'fk_i_parent_id' => NULL, 's_name' => __('Pets')),
    array('pk_i_id' => 7,   'i_position' => 7,  'fk_i_parent_id' => NULL, 's_name' => __('Kids & Baby')),
    array('pk_i_id' => 8,   'i_position' => 8,  'fk_i_parent_id' => NULL, 's_name' => __('Jobs')),
    array('pk_i_id' => 9,   'i_position' => 9,  'fk_i_parent_id' => NULL, 's_name' => __('Books, CDs & Hobbies ')),
    array('pk_i_id' => 10,  'i_position' => 10,  'fk_i_parent_id' => NULL, 's_name' => __('Automobiles')),
    array('pk_i_id' => 11,  'i_position' => 11,  'fk_i_parent_id' => NULL, 's_name' => __('Real estate')),
    array('pk_i_id' => 12,  'i_position' => 12,  'fk_i_parent_id' => NULL, 's_name' => __('Sports & Health')),
    array('pk_i_id' => 13,  'i_position' => 13,  'fk_i_parent_id' => NULL, 's_name' => __('Community')),
	array('pk_i_id' => 51,  'i_position' => 1, 'fk_i_parent_id' => 1, 's_name' => __('Mobile Phones')),
	array('pk_i_id' => 52,  'i_position' => 3, 'fk_i_parent_id' => 1, 's_name' => __('Mobile Accessories')),
	array('pk_i_id' => 53,  'i_position' => 2, 'fk_i_parent_id' => 1, 's_name' => __('Tablets')),
	array('pk_i_id' => 54,  'i_position' => 1, 'fk_i_parent_id' => 2, 's_name' => __('Furniture')),
	array('pk_i_id' => 55,  'i_position' => 2, 'fk_i_parent_id' => 2, 's_name' => __('Decor & Furnishings')),
	array('pk_i_id' => 56,  'i_position' => 3, 'fk_i_parent_id' => 2, 's_name' => __('Fridge - AC - Washing Machine')),
	array('pk_i_id' => 57,  'i_position' => 4, 'fk_i_parent_id' => 2, 's_name' => __('Home & Kitchen Appliances')),
	array('pk_i_id' => 58,  'i_position' => 5, 'fk_i_parent_id' => 2, 's_name' => __('Art - Paintings')),
	array('pk_i_id' => 59,  'i_position' => 6, 'fk_i_parent_id' => 2, 's_name' => __('Other Household Goods')),
	array('pk_i_id' => 60,  'i_position' => 1, 'fk_i_parent_id' => 3, 's_name' => __('Clothes')),
	array('pk_i_id' => 61,  'i_position' => 2, 'fk_i_parent_id' => 3, 's_name' => __('Jewellery')),
	array('pk_i_id' => 62,  'i_position' => 3, 'fk_i_parent_id' => 3, 's_name' => __('Bags & Luggage')),
	array('pk_i_id' => 63,  'i_position' => 4, 'fk_i_parent_id' => 3, 's_name' => __('Footwear')),
	array('pk_i_id' => 64,  'i_position' => 5, 'fk_i_parent_id' => 3, 's_name' => __('Clothing Accessories')),
	array('pk_i_id' => 65,  'i_position' => 6, 'fk_i_parent_id' => 3, 's_name' => __('Watches')),
	array('pk_i_id' => 66,  'i_position' => 1, 'fk_i_parent_id' => 4, 's_name' => __('Education & Classes')),
	array('pk_i_id' => 67,  'i_position' => 2, 'fk_i_parent_id' => 4, 's_name' => __('Electronics - Computers')),
	array('pk_i_id' => 68,  'i_position' => 3, 'fk_i_parent_id' => 4, 's_name' => __('Maids & Domestic Help')),
	array('pk_i_id' => 69,  'i_position' => 4, 'fk_i_parent_id' => 4, 's_name' => __('Health & Beauty')),
	array('pk_i_id' => 70,  'i_position' => 5, 'fk_i_parent_id' => 4, 's_name' => __('Home Improvements & Repairs')),
	array('pk_i_id' => 71,  'i_position' => 6, 'fk_i_parent_id' => 4, 's_name' => __('Movers & Packers')),
	array('pk_i_id' => 72,  'i_position' => 7, 'fk_i_parent_id' => 4, 's_name' => __('Drivers - Taxi Services')),
	array('pk_i_id' => 73,  'i_position' => 8, 'fk_i_parent_id' => 4, 's_name' => __('Car Wash & Repair')),
	array('pk_i_id' => 74,  'i_position' => 9, 'fk_i_parent_id' => 4, 's_name' => __('Other Services')),
	array('pk_i_id' => 75,  'i_position' => 1, 'fk_i_parent_id' => 5, 's_name' => __('Cameras & Accessories')),
	array('pk_i_id' => 76,  'i_position' => 2, 'fk_i_parent_id' => 5, 's_name' => __('TV - Video - Audio')),
	array('pk_i_id' => 77,  'i_position' => 3, 'fk_i_parent_id' => 5, 's_name' => __('Computers - Laptops')),
	array('pk_i_id' => 78,  'i_position' => 4, 'fk_i_parent_id' => 5, 's_name' => __('Computer Accessories')),
	array('pk_i_id' => 79,  'i_position' => 5, 'fk_i_parent_id' => 5, 's_name' => __('Video Games - Consoles')),
	array('pk_i_id' => 80,  'i_position' => 6, 'fk_i_parent_id' => 5, 's_name' => __('Others Electronics')),
	array('pk_i_id' => 81,  'i_position' => 1, 'fk_i_parent_id' => 6, 's_name' => __('Animals & Birds')),
	array('pk_i_id' => 82,  'i_position' => 2, 'fk_i_parent_id' => 6, 's_name' => __('Pet Food - Accessories')),
	array('pk_i_id' => 83,  'i_position' => 3, 'fk_i_parent_id' => 6, 's_name' => __('Pet Care & Services')),
	array('pk_i_id' => 84,  'i_position' => 1, 'fk_i_parent_id' => 7, 's_name' => __('Baby Products & Furniture')),
	array('pk_i_id' => 85,  'i_position' => 2, 'fk_i_parent_id' => 7, 's_name' => __('Kids Clothing - Accessories')),
	array('pk_i_id' => 86,  'i_position' => 3, 'fk_i_parent_id' => 7, 's_name' => __('Toys & Games')),
	array('pk_i_id' => 87,  'i_position' => 4, 'fk_i_parent_id' => 7, 's_name' => __('Kids Health - Nutrition')),
	array('pk_i_id' => 88,  'i_position' => 1, 'fk_i_parent_id' => 9, 's_name' => __('Books & Magazines')),
	array('pk_i_id' => 89,  'i_position' => 2, 'fk_i_parent_id' => 9, 's_name' => __('CDs - DVDs')),
	array('pk_i_id' => 90,  'i_position' => 3, 'fk_i_parent_id' => 9, 's_name' => __('Musical Instruments')),
	array('pk_i_id' => 91,  'i_position' => 4, 'fk_i_parent_id' => 9, 's_name' => __('Coins & Collectibles')),
	array('pk_i_id' => 92,  'i_position' => 5, 'fk_i_parent_id' => 10, 's_name' => __('Cars')),
	array('pk_i_id' => 93,  'i_position' => 1, 'fk_i_parent_id' => 10, 's_name' => __('Motorcycles - Scooters')),
	array('pk_i_id' => 94,  'i_position' => 2, 'fk_i_parent_id' => 10, 's_name' => __('Commercial - Transportation')),
	array('pk_i_id' => 95,  'i_position' => 3, 'fk_i_parent_id' => 10, 's_name' => __('Spare Parts - Accessories')),
	array('pk_i_id' => 96,  'i_position' => 4, 'fk_i_parent_id' => 10, 's_name' => __('Tractors - Agricultural Equipments')),
	array('pk_i_id' => 97,  'i_position' => 1, 'fk_i_parent_id' => 11, 's_name' => __('Houses - Apartments for Sale')),
	array('pk_i_id' => 98,  'i_position' => 2, 'fk_i_parent_id' => 11, 's_name' => __('Houses - Apartments for Rent')),
	array('pk_i_id' => 99,  'i_position' => 3, 'fk_i_parent_id' => 11, 's_name' => __('Land - Plots For Sale')),
	array('pk_i_id' => 100, 'i_position' => 4, 'fk_i_parent_id' => 11, 's_name' => __('Office – Commercial Space')),
	array('pk_i_id' => 101, 'i_position' => 5, 'fk_i_parent_id' => 11, 's_name' => __('PG & Roommates')),
	array('pk_i_id' => 102, 'i_position' => 6, 'fk_i_parent_id' => 11, 's_name' => __('Vacation Rentals – Guest Houses')),
	array('pk_i_id' => 103, 'i_position' => 7, 'fk_i_parent_id' => 11, 's_name' => __('Shops for Rent - Sale')),
	array('pk_i_id' => 104, 'i_position' => 1, 'fk_i_parent_id' => 12, 's_name' => __('Sport Equipment')),
	array('pk_i_id' => 105, 'i_position' => 2, 'fk_i_parent_id' => 12, 's_name' => __('Gym & Fitness')),
	array('pk_i_id' => 106, 'i_position' => 3, 'fk_i_parent_id' => 12, 's_name' => __('Health & Beauty')),
	array('pk_i_id' => 107, 'i_position' => 1, 'fk_i_parent_id' => 13, 's_name' => __('Carpool')),
	array('pk_i_id' => 108, 'i_position' => 2, 'fk_i_parent_id' => 13, 's_name' => __('Community Activities')),
	array('pk_i_id' => 109, 'i_position' => 3, 'fk_i_parent_id' => 13, 's_name' => __('Events')),
	array('pk_i_id' => 110, 'i_position' => 4, 'fk_i_parent_id' => 13, 's_name' => __('Musicians - Artists - Bands'))
	
);


$item = array(
    'catId' => 9,
    'title' => __('Example Ad'),
    'description' => __('Description of the example ad. Insert here some usefull description of your ad.'),
    'contactName' => __('Example author'),
    'contactEmail' => __('osclass@example.com'),
    'country' => __('Example country'),
    'region' => __('Example region'),
    'city' => __('Example city'),
);


$page = array(
    's_title' => __('Example page title'),
    's_text' => __('This is an example page description. This is a good place to put your Terms of Service or any other help information.'),
    's_internal_name' => 'example_page'
);

// EOF: ./dq-includes/osclass/installer/basic_data.php